# You can create this variable in settings -> gitlab -> CI/CD -> Variable
# $DH_USERNAME
# $DH_PASSWORD
image: docker:latest

variables:
  REPOSITORY_URL: $DH_USERNAME/todoapi # Perbarui ini untuk menggunakan username sebagai bagian dari REPOSITORY_URL
  IMAGE_TAG: latest

services:
  - docker:dind

before_script:
  - docker login --username=$DH_USERNAME --password=$DH_PASSWORD
  - export PORT=$PORT # Atur nilai PORT sesuai dengan kebutuhan Anda

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build -t todoapi:$IMAGE_TAG --build-arg PORT=$PORT --no-cache .
    - echo "Tagging image..."
    - docker tag todoapi:$IMAGE_TAG $REPOSITORY_URL:$IMAGE_TAG
    - echo "Pushing image..."
    - docker push $REPOSITORY_URL:$IMAGE_TAG
  only:
    - main # Mengganti "master" ke "main" sesuai dengan branch default GitLab

deploy:
  stage: deploy
  script:
    - docker stop todoapi || true && docker rm todoapi || true
    - docker container run -dt -p $PORT:$PORT --name todoapi $REPOSITORY_URL:$IMAGE_TAG
    - docker image prune -f
  only:
    - main # Mengganti "master" ke "main" sesuai dengan branch default GitLab
